/* eslint-disable */
// Generated by Wrangler by running `wrangler types --strict-vars false --include-runtime false` (hash: 869ac3b4ce0f52ba3b2e0bc70c49089e)
declare namespace Cloudflare {
  interface Env { }
}
interface Env extends Cloudflare.Env { }
